game_data = [
    {"name": "Cristiano Ronaldo", "followers": 650000000, "nationality": "Portugal", "profession": "Footballer", "image": "images/cristiano_ronaldo.jpg"},
    {"name": "Lionel Messi", "followers": 500000000, "nationality": "Argentina", "profession": "Footballer"},
    {"name": "Selena Gomez", "followers": 430000000, "nationality": "USA", "profession": "Singer"},
    {"name": "Dwayne Johnson", "followers": 400000000, "nationality": "USA", "profession": "Actor"},
    {"name": "Ariana Grande", "followers": 380000000, "nationality": "USA", "profession": "Singer"},
    {"name": "Kim Kardashian", "followers": 360000000, "nationality": "USA", "profession": "TV Personality"},
    {"name": "Beyoncé", "followers": 320000000, "nationality": "USA", "profession": "Singer"},
    {"name": "Khloé Kardashian", "followers": 310000000, "nationality": "USA", "profession": "TV Personality"},
    {"name": "Nike", "followers": 300000000, "nationality": "USA", "profession": "Brand"},
    {"name": "Justin Bieber", "followers": 290000000, "nationality": "Canada", "profession": "Singer"},
    {"name": "Taylor Swift", "followers": 280000000, "nationality": "USA", "profession": "Singer"},
    {"name": "National Geographic", "followers": 270000000, "nationality": "USA", "profession": "Media"},
    {"name": "Virat Kohli", "followers": 260000000, "nationality": "India", "profession": "Cricketer"},
    {"name": "Jennifer Lopez", "followers": 250000000, "nationality": "USA", "profession": "Singer/Actor"},
    {"name": "Nicki Minaj", "followers": 230000000, "nationality": "Trinidad and Tobago", "profession": "Rapper"},
    {"name": "Kourtney Kardashian", "followers": 220000000, "nationality": "USA", "profession": "TV Personality"},
    {"name": "Miley Cyrus", "followers": 210000000, "nationality": "USA", "profession": "Singer"},
    {"name": "Neymar", "followers": 200000000, "nationality": "Brazil", "profession": "Footballer"},
    {"name": "Katy Perry", "followers": 190000000, "nationality": "USA", "profession": "Singer"},
    {"name": "Zendaya", "followers": 180000000, "nationality": "USA", "profession": "Actress"},
    {"name": "Tom Cruise", "followers": 170000000, "nationality": "USA", "profession": "Actor"},
    {"name": "Kevin Hart", "followers": 160000000, "nationality": "USA", "profession": "Comedian"},
    {"name": "Cardi B", "followers": 150000000, "nationality": "USA", "profession": "Rapper"},
    {"name": "LeBron James", "followers": 140000000, "nationality": "USA", "profession": "Basketball Player"},
    {"name": "Demi Lovato", "followers": 130000000, "nationality": "USA", "profession": "Singer"},
    {"name": "Rihanna", "followers": 120000000, "nationality": "Barbados", "profession": "Singer"},
    {"name": "Shakira", "followers": 110000000, "nationality": "Colombia", "profession": "Singer"},
    {"name": "Chris Hemsworth", "followers": 100000000, "nationality": "Australia", "profession": "Actor"},
    {"name": "Priyanka Chopra", "followers": 95000000, "nationality": "India", "profession": "Actress"},
    {"name": "Billie Eilish", "followers": 90000000, "nationality": "USA", "profession": "Singer"},
    {"name": "Emma Watson", "followers": 85000000, "nationality": "UK", "profession": "Actress"},
    {"name": "Gigi Hadid", "followers": 80000000, "nationality": "USA", "profession": "Model"},
    {"name": "Shawn Mendes", "followers": 75000000, "nationality": "Canada", "profession": "Singer"},
    {"name": "Bruno Mars", "followers": 70000000, "nationality": "USA", "profession": "Singer"},
    {"name": "Adele", "followers": 65000000, "nationality": "UK", "profession": "Singer"},
    {"name": "Ed Sheeran", "followers": 60000000, "nationality": "UK", "profession": "Singer"},
    {"name": "Michael Jordan", "followers": 55000000, "nationality": "USA", "profession": "Basketball Player"},
    {"name": "Oprah Winfrey", "followers": 50000000, "nationality": "USA", "profession": "TV Host"},
    {"name": "Will Smith", "followers": 45000000, "nationality": "USA", "profession": "Actor"},
    {"name": "Angelina Jolie", "followers": 40000000, "nationality": "USA", "profession": "Actress"},
    {"name": "Brad Pitt", "followers": 35000000, "nationality": "USA", "profession": "Actor"},
    {"name": "Scarlett Johansson", "followers": 30000000, "nationality": "USA", "profession": "Actress"},
    {"name": "Johnny Depp", "followers": 25000000, "nationality": "USA", "profession": "Actor"},
    {"name": "Leonardo DiCaprio", "followers": 20000000, "nationality": "USA", "profession": "Actor"},
    {"name": "Tom Hanks", "followers": 15000000, "nationality": "USA", "profession": "Actor"},
    {"name": "Morgan Freeman", "followers": 10000000, "nationality": "USA", "profession": "Actor"},
    {"name": "Denzel Washington", "followers": 5000000, "nationality": "USA", "profession": "Actor"},
    {"name": "Meryl Streep", "followers": 2000000, "nationality": "USA", "profession": "Actress"},
    {"name": "Julia Roberts", "followers": 1000000, "nationality": "USA", "profession": "Actress"},
    {"name": "George Clooney", "followers": 500000, "nationality": "USA", "profession": "Actor"},
    {"name": "Nicole Kidman", "followers": 200000, "nationality": "Australia", "profession": "Actress"},
    {"name": "Hugh Jackman", "followers": 100000, "nationality": "Australia", "profession": "Actor"},
    {"name": "Cate Blanchett", "followers": 50000, "nationality": "Australia", "profession": "Actress"},
    {"name": "Russell Crowe", "followers": 20000, "nationality": "Australia", "profession": "Actor"},
    {"name": "Margot Robbie", "followers": 10000, "nationality": "Australia", "profession": "Actress"},
    {"name": "Chris Pratt", "followers": 5000, "nationality": "USA", "profession": "Actor"},
    {"name": "Ryan Reynolds", "followers": 2000, "nationality": "Canada", "profession": "Actor"},
    {"name": "Mark Wahlberg", "followers": 1000, "nationality": "USA", "profession": "Actor"},
    {"name": "Ben Affleck", "followers": 500, "nationality": "USA", "profession": "Actor"},
    {"name": "Matt Damon", "followers": 200, "nationality": "USA", "profession": "Actor"},
    {"name": "Christian Bale", "followers": 100, "nationality": "UK", "profession": "Actor"},
    {"name": "Heath Ledger", "followers": 50, "nationality": "Australia", "profession": "Actor"},
    {"name": "Joaquin Phoenix", "followers": 20, "nationality": "USA", "profession": "Actor"},
    {"name": "Jared Leto", "followers": 10, "nationality": "USA", "profession": "Actor"},
    {"name": "Javier Bardem", "followers": 5, "nationality": "Spain", "profession": "Actor"},
    {"name": "Antonio Banderas", "followers": 2, "nationality": "Spain", "profession": "Actor"},
    {"name": "Penélope Cruz", "followers": 1, "nationality": "Spain", "profession": "Actress"},
    {"name": "Salma Hayek", "followers": 0.5, "nationality": "Mexico", "profession": "Actress"},
    {"name": "Gael García Bernal", "followers": 0.2, "nationality": "Mexico", "profession": "Actor"},
    {"name": "Diego Luna", "followers": 0.1, "nationality": "Mexico", "profession": "Actor"},
    {"name": "Kate Winslet", "followers": 0.05, "nationality": "UK", "profession": "Actress"},
    {"name": "Ralph Fiennes", "followers": 0.02, "nationality": "UK", "profession": "Actor"},
    {"name": "Helena Bonham Carter", "followers": 0.01, "nationality": "UK", "profession": "Actress"},
    {"name": "Tim Burton", "followers": 0.005, "nationality": "USA", "profession": "Director"},
    {"name": "Johnny Depp", "followers": 0.002, "nationality": "USA", "profession": "Actor"},
    {"name": "Winona Ryder", "followers": 0.001, "nationality": "USA", "profession": "Actress"},
    {"name": "Christina Ricci", "followers": 0.0005, "nationality": "USA", "profession": "Actress"},
    {"name": "Drew Barrymore", "followers": 0.0002, "nationality": "USA", "profession": "Actress"},
    {"name": "Cameron Diaz", "followers": 0.0001, "nationality": "USA", "profession": "Actress"},
    {"name": "Lucy Liu", "followers": 0.00005, "nationality": "USA", "profession": "Actress"},
    {"name": "Zhang Ziyi", "followers": 0.00002, "nationality": "China", "profession": "Actress"},
    {"name": "Gong Li", "followers": 0.00001, "nationality": "China", "profession": "Actress"},
    {"name": "Jet Li", "followers": 0.000005, "nationality": "China", "profession": "Actor"},
    {"name": "Jackie Chan", "followers": 0.000002, "nationality": "China", "profession": "Actor"},
    {"name": "Bruce Lee", "followers": 0.000001, "nationality": "USA", "profession": "Actor"},
    {"name": "Arnold Schwarzenegger", "followers": 0.0000005, "nationality": "Austria", "profession": "Actor"},
    {"name": "Sylvester Stallone", "followers": 0.0000002, "nationality": "USA", "profession": "Actor"},
    {"name": "Jean-Claude Van Damme", "followers": 0.0000001, "nationality": "Belgium", "profession": "Actor"},
    {"name": "Chuck Norris", "followers": 0.00000005, "nationality": "USA", "profession": "Actor"},
    {"name": "Steven Seagal", "followers": 0.00000002, "nationality": "USA", "profession": "Actor"},
    {"name": "Wesley Snipes", "followers": 0.00000001, "nationality": "USA", "profession": "Actor"},
    {"name": "Samuel L. Jackson", "followers": 0.000000005, "nationality": "USA", "profession": "Actor"},
    {"name": "Laurence Fishburne", "followers": 0.000000002, "nationality": "USA", "profession": "Actor"},
    {"name": "Morgan Freeman", "followers": 0.000000001, "nationality": "USA", "profession": "Actor"},
    {"name": "Clint Eastwood", "followers": 0.0000000005, "nationality": "USA", "profession": "Actor"},
    {"name": "John Wayne", "followers": 0.0000000002, "nationality": "USA", "profession": "Actor"},
    {"name": "Gary Cooper", "followers": 0.0000000001, "nationality": "USA", "profession": "Actor"},
    {"name": "Henry Fonda", "followers": 0.00000000005, "nationality": "USA", "profession": "Actor"},
    {"name": "James Stewart", "followers": 0.00000000002, "nationality": "USA", "profession": "Actor"},
    {"name": "Cary Grant", "followers": 0.00000000001, "nationality": "USA", "profession": "Actor"},
    {"name": "Humphrey Bogart", "followers": 0.000000000005, "nationality": "USA", "profession": "Actor"},
    {"name": "Bette Davis", "followers": 0.000000000002, "nationality": "USA", "profession": "Actress"},
    {"name": "Katharine Hepburn", "followers": 0.000000000001, "nationality": "USA", "profession": "Actress"},
    {"name": "Ingrid Bergman", "followers": 0.0000000000005, "nationality": "Sweden", "profession": "Actress"},
    {"name": "Greta Garbo", "followers": 0.0000000000002, "nationality": "Sweden", "profession": "Actress"},
    {"name": "Marlene Dietrich", "followers": 0.0000000000001, "nationality": "Germany", "profession": "Actress"},
    {"name": "Lana Turner", "followers": 0.00000000000005, "nationality": "USA", "profession": "Actress"},
    {"name": "Rita Hayworth", "followers": 0.00000000000002, "nationality": "USA", "profession": "Actress"},
    {"name": "Ava Gardner", "followers": 0.00000000000001, "nationality": "USA", "profession": "Actress"},
]